# Generated by Django 5.0.4 on 2024-05-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities_static", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="SSN",
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="authentication_hash",
            field=models.CharField(max_length=256),
        ),
    ]
