# Generated by Django 5.0.6 on 2024-05-13 17:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('utilities_static', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ssn', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('info', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_ssn', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cover_letter', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities_static.status')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.application')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.education')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.application')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.recommendation')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.application')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.application')),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.experience')),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default='1990-01-01')),
                ('job_title', models.CharField(default='None', max_length=100)),
                ('salary_low', models.IntegerField()),
                ('salary_high', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities_static.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities_static.employmenttype')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.recruiter')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.joblisting'),
        ),
        migrations.AddField(
            model_name='application',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.recruiter'),
        ),
    ]
