# Generated by Django 5.0.6 on 2024-05-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiter",
            name="company_ssn",
            field=models.CharField(max_length=15),
        ),
    ]
