# Generated by Django 5.0.4 on 2024-05-08 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("utilities_static", "0002_alter_user_ssn_alter_user_authentication_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="company.joblisting",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_applications",
                to="utilities_static.status",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_applications",
                to="utilities_static.user",
            ),
        ),
    ]
