# Generated by Django 5.0.6 on 2024-05-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_recruiter_company_ssn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_ssn",
            field=models.CharField(max_length=15),
        ),
    ]
