# Generated by Django 5.0.6 on 2024-05-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_company_company_ssn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
