# Generated by Django 5.0.6 on 2024-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_company_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
