# Generated by Django 5.0.6 on 2024-05-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0001_initial"),
        ("company", "0006_alter_application_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="user",
        ),
        migrations.AddField(
            model_name="application",
            name="applicant",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="recruiter",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.recruiter",
            ),
            preserve_default=False,
        ),
    ]
