# Generated by Django 5.0.6 on 2024-05-09 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_remove_application_user_application_applicant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="company.joblisting"
            ),
        ),
    ]
