# Generated by Django 5.0.4 on 2024-05-08 09:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0001_initial"),
        ("company", "0002_alter_application_listing_alter_application_status_and_more"),
        ("utilities_static", "0002_alter_user_ssn_alter_user_authentication_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="applicant",
            field=models.ForeignKey(
                default=-4,
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recommendation",
            name="applicant",
            field=models.ForeignKey(
                default=-4,
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="applicant",
            field=models.ForeignKey(
                default=-4,
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.joblisting",
                    ),
                ),
                (
                    "status",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utilities_static.status",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utilities_static.user",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="applicationrecommendations",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applicant.application"
            ),
        ),
        migrations.AlterField(
            model_name="applicationresume",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applicant.application"
            ),
        ),
        migrations.AlterField(
            model_name="applicationworkexperience",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applicant.application"
            ),
        ),
        migrations.DeleteModel(
            name="ApplicationEducation",
        ),
    ]
