# Generated by Django 5.0.4 on 2024-05-08 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0002_experience_applicant_recommendation_applicant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicant.application",
                    ),
                ),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicant.education",
                    ),
                ),
            ],
        ),
    ]
